services:
  catalog.database:
    image: bitnami/postgresql
    container_name: catalog.database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_DATABASE: catalog
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_TIMEZONE: America/Sao_Paulo
  orders.database:
    image: bitnami/postgresql
    container_name: orders.database
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRESQL_DATABASE: orders
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_TIMEZONE: America/Sao_Paulo
  payments.database:
    image: bitnami/postgresql
    container_name: payments.database
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRESQL_DATABASE: orders
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_TIMEZONE: America/Sao_Paulo

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin