name: Catalog CI

on:    
  push:
    branches: [ main ]
    paths:
      - 'contexts/catalog/**'
      - 'contexts/shared/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'contexts/catalog/**'
      - 'contexts/shared/**'

jobs:
  build-and-test-catalog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore contexts/catalog/src/Ecomm.Catalog.WebApi/Ecomm.Catalog.WebApi.csproj
      
    - name: Build Catalog API
      run: dotnet build contexts/catalog/src/Ecomm.Catalog.WebApi/Ecomm.Catalog.WebApi.csproj --no-restore --configuration Release

  docker-build-catalog:
    runs-on: ubuntu-latest
    needs: build-and-test-catalog
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ecomm-catalog-api
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Catalog API Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: contexts/catalog/src/Ecomm.Catalog.WebApi/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_CONFIGURATION=Release
        cache-from: type=gha
        cache-to: type=gha,mode=max
