name: Shared Components CI

on:
  push:
    branches: [ main ]
    paths:
      - 'contexts/shared/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'contexts/shared/**'

jobs:
  build-and-test-shared:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore Shared SeedWork dependencies
      run: dotnet restore contexts/shared/domain/Ecomm.Shared.SeedWork/Ecomm.Shared.SeedWork.csproj
      
    - name: Build Shared SeedWork
      run: dotnet build contexts/shared/domain/Ecomm.Shared.SeedWork/Ecomm.Shared.SeedWork.csproj --no-restore --configuration Release
      
    - name: Restore Shared Infrastructure dependencies
      run: dotnet restore contexts/shared/infrastructure/Ecomm.Shared.Infrastructure/Ecomm.Shared.Infrastructure.csproj
      
    - name: Build Shared Infrastructure
      run: dotnet build contexts/shared/infrastructure/Ecomm.Shared.Infrastructure/Ecomm.Shared.Infrastructure.csproj --no-restore --configuration Release
      
    - name: Restore Aspire ServiceDefaults dependencies
      run: dotnet restore contexts/shared/aspire/Aspire.ServiceDefaults/Aspire.ServiceDefaults.csproj
      
    - name: Build Aspire ServiceDefaults
      run: dotnet build contexts/shared/aspire/Aspire.ServiceDefaults/Aspire.ServiceDefaults.csproj --no-restore --configuration Release
      
    - name: Restore Aspire AppHost dependencies
      run: dotnet restore contexts/shared/aspire/Aspire.AppHost/Aspire.AppHost.csproj
      
    - name: Build Aspire AppHost
      run: dotnet build contexts/shared/aspire/Aspire.AppHost/Aspire.AppHost.csproj --no-restore --configuration Release
